aws_database:
  hostname: ''
  port: '3306'
  username: ''
  password: ''
  
gcp_database:
  hostname: ''
  port: ''
  username: 'root'
  password: ''
  
local_database:
  hostname: 'localhost'
  port: '3306'
  username: 'root'
  password: ''

email_detail:
  email: 'franklintest03@gmail.com'
  password: ''